# Site settings
title: Thijs Brobbel's Tech blog
email: thijsbrobbel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my own little blog for writing about my adventures with C#, WPF, GIT,
  Roslyn, and all other stuff that comes on my path ;)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tiesmaster.github.io" # the base hostname & protocol for your site
twitter_username: tiesmaster
github_username:  tiesmaster

# Build settings
markdown: kramdown
